define DEPENDABLE_VAR

.PHONY: phony
${BUILD_DIR}/.$1: | ${BUILD_DIR}
	echo -n $($1) > ${BUILD_DIR}/.$1 ; \

ifneq ("$(file <${BUILD_DIR}/.$1)","$($(1))")
${BUILD_DIR}/.$1: phony
endif

endef

$(eval $(call DEPENDABLE_VAR,SYNTH_SRC))
$(eval $(call DEPENDABLE_VAR,SIM_SRC))
$(eval $(call DEPENDABLE_VAR,SIM_TB))
$(eval $(call DEPENDABLE_VAR,TOP))

$(eval $(call DEPENDABLE_VAR,PRE_SYNTH_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,POST_SYNTH_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,PROBES_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,PRE_OPT_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,POST_OPT_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,PRE_PLACEMENT_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,POST_PLACEMENT_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,PRE_ROUTE_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,POST_ROUTE_CONSTRAINTS))
$(eval $(call DEPENDABLE_VAR,PRE_BITSTREAM_CONSTRAINTS))

$(eval $(call DEPENDABLE_VAR,SYNTHESIS_DIRECTIVE))
$(eval $(call DEPENDABLE_VAR,OPT_DESIGN_DIRECTIVE))
$(eval $(call DEPENDABLE_VAR,PLACEMENT_DIRECTIVE))
$(eval $(call DEPENDABLE_VAR,ROUTE_DIRECTIVE))
$(eval $(call DEPENDABLE_VAR,USE_PROBES))

SYNTH_SRC_DEP = ${BUILD_DIR}/.SYNTH_SRC
SIM_SRC_DEP   = ${BUILD_DIR}/.SIM_SRC
SIM_TB_DEP    = ${BUILD_DIR}/.SIM_TB
TOP_DEP       = ${BUILD_DIR}/.TOP

PRE_SYNTH_CONSTRAINTS_DEP      = ${BUILD_DIR}/.PRE_SYNTH_CONSTRAINTS
POST_SYNTH_CONSTRAINTS_DEP     = ${BUILD_DIR}/.POST_SYNTH_CONSTRAINTS
PROBES_CONSTRAINTS_DEP         = ${BUILD_DIR}/.PROBES_CONSTRAINTS
PRE_OPT_CONSTRAINTS_DEP        = ${BUILD_DIR}/.PRE_OPT_CONSTRAINTS
POST_OPT_CONSTRAINTS_DEP       = ${BUILD_DIR}/.POST_OPT_CONSTRAINTS
PRE_PLACEMENT_CONSTRAINTS_DEP  = ${BUILD_DIR}/.PRE_PLACEMENT_CONSTRAINTS
POST_PLACEMENT_CONSTRAINTS_DEP = ${BUILD_DIR}/.POST_PLACEMENT_CONSTRAINTS
PRE_ROUTE_CONSTRAINTS_DEP      = ${BUILD_DIR}/.PRE_ROUTE_CONSTRAINTS
POST_ROUTE_CONSTRAINTS_DEP     = ${BUILD_DIR}/.POST_ROUTE_CONSTRAINTS
PRE_BITSTREAM_CONSTRAINTS_DEP  = ${BUILD_DIR}/.PRE_BITSTREAM_CONSTRAINTS

SYNTHESIS_DIRECTIVE_DEP  = ${BUILD_DIR}/.SYNTHESIS_DIRECTIVE
OPT_DESIGN_DIRECTIVE_DEP = ${BUILD_DIR}/.OPT_DESIGN_DIRECTIVE
PLACEMENT_DIRECTIVE_DEP  = ${BUILD_DIR}/.PLACEMENT_DIRECTIVE
ROUTE_DIRECTIVE_DEP      = ${BUILD_DIR}/.ROUTE_DIRECTIVE
USE_PROBES_DEP           = ${BUILD_DIR}/.USE_PROBES

SYNTH_IMPORT_VAR_DEPS = ${SYNTH_SRC_DEP}
SYNTH_VAR_DEPS        = ${PRE_SYNTH_CONSTRAINTS_DEP} ${POST_SYNTH_CONSTRAINTS_DEP} ${SYNTHESIS_DIRECTIVE_DEP} ${TOP_DEP}
OPT_DESIGN_VAR_DEPS   = ${PRE_OPT_CONSTRAINTS_DEP} ${POST_OPT_CONSTRAINTS_DEP} ${PROBES_CONSTRAINTS_DEP} ${OPT_DESIGN_DIRECTIVE_DEP} ${USE_PROBES_DEP}
PLACEMENT_VAR_DEPS    = ${PRE_PLACEMENT_CONSTRAINTS_DEP} ${POST_PLACEMENT_CONSTRAINTS_DEP} ${PLACEMENT_DIRECTIVE_DEP}
ROUTE_VAR_DEPS        = ${PRE_ROUTE_CONSTRAINTS_DEP} ${POST_ROUTE_CONSTRAINTS_DEP} ${ROUTE_DIRECTIVE_DEP}
BITSTREAM_VAR_DEPS    = ${PRE_BITSTREAM_CONSTRAINTS_DEP}
SIM_COMPILE_VAR_DEPS  = ${SIM_SRC_DEP} ${SIM_TB_DEP}

define BM_DEPENDABLE_VAR

.PHONY: phony
${BUILD_DIR}/.${BM_PROJECT}-$1: | ${BUILD_DIR}
	echo -n $($1) > ${BUILD_DIR}/.${BM_PROJECT}-$1 ; \

ifneq ("$(file <${BUILD_DIR}/.${BM_PROJECT}-$1)","$($(1))")
${BUILD_DIR}/.${BM_PROJECT}-$1: phony
endif

endef

$(eval $(call BM_DEPENDABLE_VAR,BARE_METAL_C))
$(eval $(call BM_DEPENDABLE_VAR,BARE_METAL_H))
$(eval $(call BM_DEPENDABLE_VAR,BM_STACK_SIZE))
$(eval $(call BM_DEPENDABLE_VAR,BM_HEAP_SIZE))

BARE_METAL_C_DEP = ${BUILD_DIR}/.${BM_PROJECT}-BARE_METAL_C
BARE_METAL_H_DEP = ${BUILD_DIR}/.${BM_PROJECT}-BARE_METAL_H
BARE_METAL_STACK_SIZE_DEP = ${BUILD_DIR}/.${BM_PROJECT}-BM_STACK_SIZE
BARE_METAL_HEAP_SIZE_DEP  = ${BUILD_DIR}/.${BM_PROJECT}-BM_HEAP_SIZE

BAREMETAL_BUILD_DEPS = ${BARE_METAL_C_DEP} ${BARE_METAL_H_DEP} ${BARE_METAL_STACK_SIZE_DEP} ${BARE_METAL_HEAP_SIZE_DEP}

define FREERTOS_DEPENDABLE_VAR

.PHONY: phony
${BUILD_DIR}/.${FREE_RTOS_PROJECT}-$1: | ${BUILD_DIR}
	echo -n $($1) > ${BUILD_DIR}/.${FREE_RTOS_PROJECT}-$1 ; \

ifneq ("$(file <${BUILD_DIR}/.${FREE_RTOS_PROJECT}-$1)","$($(1))")
${BUILD_DIR}/.${FREE_RTOS_PROJECT}-$1: phony
endif

endef

$(eval $(call FREERTOS_DEPENDABLE_VAR,FREE_RTOS_C))
$(eval $(call FREERTOS_DEPENDABLE_VAR,FREE_RTOS_H))
$(eval $(call FREERTOS_DEPENDABLE_VAR,FREERTOS_STACK_SIZE))
$(eval $(call FREERTOS_DEPENDABLE_VAR,FREERTOS_HEAP_SIZE))

FREE_RTOS_C_DEP = ${BUILD_DIR}/.${FREE_RTOS_PROJECT}-FREE_RTOS_C
FREE_RTOS_H_DEP = ${BUILD_DIR}/.${FREE_RTOS_PROJECT}-FREE_RTOS_H
FREE_RTOS_STACK_SIZE_DEP = ${BUILD_DIR}/.${FREE_RTOS_PROJECT}-FREERTOS_STACK_SIZE
FREE_RTOS_HEAP_SIZE_DEP  = ${BUILD_DIR}/.${FREE_RTOS_PROJECT}-FREERTOS_HEAP_SIZE

FREE_RTOS_BUILD_DEPS = ${FREE_RTOS_C_DEP} ${FREE_RTOS_H_DEP} ${FREE_RTOS_STACK_SIZE_DEP} ${FREE_RTOS_HEAP_SIZE_DEP}
